#!/bin/sh

set -eu

robot_target_dir=$1
robot_script=$2

cp "$robot_script" "${robot_target_dir}/.robot.tcl"

for user in $(getent passwd | awk -F: '$3 >= 10000 { print $1 }'); do
  ln -f "${robot_target_dir}/.robot.tcl" "${robot_target_dir}/${user}.robot"
done
